# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ohflash_dialog3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OHFlashDialog3(object):
    def setupUi(self, OHFlashDialog3):
        OHFlashDialog3.setObjectName("OHFlashDialog3")
        OHFlashDialog3.resize(379, 127)
        self.formLayout_2 = QtWidgets.QFormLayout(OHFlashDialog3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.IDlabel = QtWidgets.QLabel(OHFlashDialog3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IDlabel.setFont(font)
        self.IDlabel.setObjectName("IDlabel")
        self.gridLayout.addWidget(self.IDlabel, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(OHFlashDialog3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.buttonContainer = QtWidgets.QVBoxLayout()
        self.buttonContainer.setObjectName("buttonContainer")
        self.gridLayout.addLayout(self.buttonContainer, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevButton = QtWidgets.QPushButton(OHFlashDialog3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prevButton.setFont(font)
        self.prevButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.quitButton = QtWidgets.QPushButton(OHFlashDialog3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quitButton.setFont(font)
        self.quitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout_2.addWidget(self.quitButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)

        self.retranslateUi(OHFlashDialog3)
        QtCore.QMetaObject.connectSlotsByName(OHFlashDialog3)

    def retranslateUi(self, OHFlashDialog3):
        _translate = QtCore.QCoreApplication.translate
        self.IDlabel.setText(_translate("OHFlashDialog3", "TextLabel"))
        self.prevButton.setText(_translate("OHFlashDialog3", "Précédent"))
        self.quitButton.setText(_translate("OHFlashDialog3", "Annuler"))
