# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ohflash_dialog3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OHFlashDialog3(object):
    def setupUi(self, OHFlashDialog3):
        OHFlashDialog3.setObjectName("OHFlashDialog3")
        OHFlashDialog3.resize(289, 146)
        self.layoutWidget = QtWidgets.QWidget(OHFlashDialog3)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 271, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.IDlabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IDlabel.setFont(font)
        self.IDlabel.setObjectName("IDlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.IDlabel)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yesButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yesButton.setFont(font)
        self.yesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.noButton.setFont(font)
        self.noButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.noButton.setObjectName("noButton")
        self.horizontalLayout.addWidget(self.noButton)
        self.otherButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.otherButton.setFont(font)
        self.otherButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.otherButton.setObjectName("otherButton")
        self.horizontalLayout.addWidget(self.otherButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prevButton.setFont(font)
        self.prevButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.quitButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quitButton.setFont(font)
        self.quitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout_2.addWidget(self.quitButton)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)

        self.retranslateUi(OHFlashDialog3)
        QtCore.QMetaObject.connectSlotsByName(OHFlashDialog3)

    def retranslateUi(self, OHFlashDialog3):
        _translate = QtCore.QCoreApplication.translate
        self.IDlabel.setText(_translate("OHFlashDialog3", "TextLabel"))
        self.yesButton.setText(_translate("OHFlashDialog3", "yesButton"))
        self.noButton.setText(_translate("OHFlashDialog3", "noButton"))
        self.otherButton.setText(_translate("OHFlashDialog3", "otherButton"))
        self.prevButton.setText(_translate("OHFlashDialog3", "Précédent"))
        self.quitButton.setText(_translate("OHFlashDialog3", "Annuler"))
